### ISSUE TITLE
Bare URLs in Markdown don't get made into links

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-template#13]
E.g. in the [IS-04 "Overview" source doc](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/1.0.%20Overview.md), `http://jt-nm.org/` is rendered as a link.* **That's nice.**

But in the [IS-04 "Overview" rendered doc](https://amwa-tv.github.io/nmos-discovery-registration/branches/v1.3.x/docs/1.0._Overview.html), that text is not rendered as a link. **That's a shame.**

*This is a "GitHub Flavor" Markdown extension, I believe.

**Comment by peterbrightwell** [comment]
@garethsb-sony in your example the source should have used `<http://jt-nm.org/>` -- linters tend to complain about bare URLs.  I didn't know that three years ago when that was written though.

This could be sorted by fix-link.sh, but better to fix the source in the next point release?

**Comment by garethsb** [comment]
Um, say again, what should the source have used... it looks like you typed the bare URL above,  but I'm guessing you didn't!? 😃

**Comment by peterbrightwell** [comment]
It should have used `<http://jt-nm.org/>`. I've updated the previous comment to this.

**Comment by peterbrightwell** [comment]
After confirming that explicitly setting Jekyll's kramdown mode to GFM didn't help, and  consideration of the various types of links that can be used in Markdown (including reference links which contain bare URLs), a consistent rewrite rule is non-trivial for the benefit gained, so best to fix source, as per e.g. https://github.com/AMWA-TV/nmos-discovery-registration/commit/4c7640f63deaea80417b41074a57e9dd8434085d
