### ISSUE TITLE
Consider adding markdown linting

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-template#8]
Recent great work to add JSON and RAML linting will make maintaining the quality of our specs easier. Linting of Markdown documentation would also help.

Looks like there are several tools out there already (choose your preference for CI, ruby, python, js) with common rule sets and the ability to extend with our own AMWA/NMOS specific rules.

For example, it's currently the case that IS-04, -05, -06, -07 all have slight inconsistencies between their `docs/` filenames, initial headings in those files, and link text to that file from others. A few regex searches across these four repos finds a few cross-links mentioning section number, while mostly they don't; also a few different styles of numbering sub-sections within a Markdown file (unnumbered; numbered as 1, 2, 2.1, 3; numbered as N.1, N.2, N.2.1, N.3; with/without trailing dot).

(This may be a separate issue, but I also find it intermittently annoying that there's no easy way of reading to the next page of the documentation, or navigating to child/parent pages, in the NMOS repos or generated docs. E.g. consider what would be useful links from https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.3/docs/2.0._APIs.html.)

**Comment by peterbrightwell** [comment]
@garethsb as you know we do have markdown linting now -- should this be closed?

**Comment by peterbrightwell** [comment]
@garethsb I shall assume yes.
